name: My Workflow

on: 
  push: 
  pull_request:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: security check
      uses: wspr-ncsu/github-actions-security-analysis/gwchecker@main

      
  goodbye: 
    runs-on: ubuntu-latest
    steps:
    - name: say goodbye to the audience
      run: echo "good bye!"

  seeyouagain: 
    runs-on: ubuntu-latest
    steps:
    - name: happy to see you guys again
      run: echo "happy to see you guys again!"
    
