name: My Workflow

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
	uses: actions/checkout@v3
      - name: workflow security check
	uses: wspr-ncsu/github-actions-security-analysis/gwchecker@main